### PR TITLE
save player names by adding them to localStorage

### PR DESCRIPTION
**Pull request by redapy**
## issue
#4
## Description
I added a local storage named "players". The state `players` is updeted on the first render to be the same as what we have in `localStorage`. 
Any changes on the `players` state will be applied to the localStrage "players" as well.
PS: I'm not very familiar with TypeScript, but I wish I did well. so if there is anything to change let me know.

### CODE REVIEW

**Comment by redapy** [comment]
I have prettier, I'll install eslint. But, I don't understand what is the problem with the formatting.(at me all the file is the same format)

**Comment by redapy** [comment]
Okay I'll try to remove spaces you don't like, and I'll work on storing only the name of players.

**Comment by redapy** [comment]
I saved only the player names (with empty scores) in `localStorage`. If there is anything with formatting let me know.

**Comment by soosgyul** [comment]
merged separately

**Pull request closed without merging**
